package com.example.anthony.financialtracking;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

/**
 * Created by Keegan on 4/20/2018.
 *
 * This class contains the Record entity for use in a Room.
 *
 * It represents a table, named Record, used to store the details of a logged
 * transaction
 */

//
@Entity(tableName = "Record")
public class Record {
    //Auto-generated id for this record: primary key
    @PrimaryKey(autoGenerate = true)
    private int r_id;

    @NonNull
    private String name;
    @NonNull
    private double amount;
    @NonNull
    private String type;
    private String location;
    @NonNull
    private long timestamp;

    /*
     * Below are simple autogenerated getter/setters
     */

    public int getR_id() {
        return r_id;
    }

    public void setR_id(int r_id) {
        this.r_id = r_id;
    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    @NonNull
    public double getAmount() {
        return amount;
    }

    public void setAmount(@NonNull double amount) {
        this.amount = amount;
    }

    @NonNull
    public String getType() {
        return type;
    }

    public void setType(@NonNull String type) {
        this.type = type;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @NonNull
    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(@NonNull long timestamp) {
        this.timestamp = timestamp;
    }
}
